name: CI

on:
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #executa o linter
      - name: Run linter
        run: npm run lint